#pragma once

#define MAX_THRESHOLD_JOINT_POSITION 6.283184
#define MIN_THRESHOLD_JOINT_POSITION -6.283184
#define MAX_THRESHOLD_JOINT_VELOCITY 3.0
#define MIN_THRESHOLD_JOINT_VELOCITY -3.0
#define MAX_THRESHOLD_JOINT_TORQUE   6.0
#define MIN_THRESHOLD_JOINT_TORQUE   -6.0
#define MAX_THRESHOLD_JOINT_CURRENT  6.0
#define MIN_THRESHOLD_JOINT_CURRENT  -6.0
